# Generated by Django 3.2.16 on 2023-01-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='type',
            field=models.CharField(choices=[('Cabinet', 'CABINET'), ('Closet', 'CLOSET'), ('Shelf', 'sHELF')], max_length=30, null=True),
        ),
    ]
