# Generated by Django 3.2.16 on 2023-01-13 03:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_alter_workspace_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='type',
            field=models.CharField(choices=[('Cabinet', 'CABINET'), ('Closet', 'CLOSET'), ('Shelf', 'sHELF')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='workspace_uuid',
            field=models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False),
        ),
    ]
