# Generated by Django 3.2.16 on 2023-01-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_auto_20230113_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='type',
            field=models.CharField(choices=[('Closet', 'CLOSET'), ('Cabinet', 'CABINET'), ('Shelf', 'sHELF')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='workspace_uuid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
