# Generated by Django 3.2.16 on 2023-01-31 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_alter_workspace_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='type',
            field=models.CharField(choices=[('Closet', 'CLOSET'), ('Shelf', 'sHELF'), ('Cabinet', 'CABINET')], max_length=30, null=True),
        ),
    ]
