# Generated by Django 3.2.16 on 2023-02-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_alter_workspace_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='type',
            field=models.CharField(choices=[('Shelf', 'sHELF'), ('Cabinet', 'CABINET'), ('Closet', 'CLOSET')], max_length=30, null=True),
        ),
    ]
