# Generated by Django 3.2.16 on 2023-02-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0008_alter_workspace_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='source',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='type',
            field=models.CharField(choices=[('Cabinet', 'CABINET'), ('Shelf', 'SHELF'), ('Closet', 'CLOSET')], max_length=30, null=True),
        ),
    ]
