# Generated by Django 3.2.16 on 2023-01-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_uuid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
