# Generated by Django 3.2.16 on 2023-01-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_product_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='In',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Out',
            field=models.BooleanField(default=True),
        ),
    ]
